### ISSUE TITLE
Log accountId and integrationInstanceId when running in deployed environment

### ISSUE THREAD

**Issue by philidem** [JupiterOne/integration-sdk#135]

**Comment by charlieduong94** [comment]
Considering that the two main functions that start an integration (`executeIntegrationInstance` and `initiateSynchronization`) accept an input logger, I'm thinking it might make a little more sense to have the `accountId` and `integrationInstanceId` be immediately added to the logger once it is created in our managed runtime environment instead of here in the sdk.

**Comment by aiwilliams** [comment]
> immediately added to the logger once it is created in our managed runtime environment instead of here in the sdk.

I think this is definitely the right place to do it. @philidem, you'll see that it can be easily added here https://bitbucket.org/lifeomic/jupiter-integration-qualys/src/c118dee650ae573cd2451f9f80d40c25f01296c3/src/lambda/index.ts#lines-37, and we'll be sure the runtime library carries that on for all the integrations.
